### ISSUE TITLE
please check this erro

### ISSUE THREAD

**Issue by emans841** [GreatSCT/GreatSCT#4]
./GreatSCT.py --ip 192.168.8.100 --port 4444 -t Bypass -p installutil/powershell/script.py -c "OBFUSCATION=ascii SCRIPT=/root/script.ps1"
Traceback (most recent call last):
  File "./GreatSCT.py", line 103, in <module>
    the_conductor.command_line_use()
  File "/root/Desktop/GreatSCT/lib/common/orchestra.py", line 38, in command_line_use
    tool_object.cli_menu()
  File "Tools/Bypass/Tool.py", line 200, in cli_menu
    user_cli_payload.generate()
  File "Tools/Bypass/payloads/installutil/powershell/script.py", line 54, in generate
    with open(self.required_options["SCRIPT"][0], "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/script.ps1'

**Comment by ConsciousHacker** [comment]
I will fix this FileNotFoundError within the next few days. In the meantime, make sure your powershell script is in the location you specify on the CLI.
